load_products_task:
  description: >
    Connect to the Shopify store using the 'Load All Store Products' tool. 
    This is the first and most important step.
  expected_output: >
    A complete JSON string listing all products from the store, including their 
    product ID, current title, body_html, tags, seo_title, and seo_description.

seo_optimization_task:
  description: >
    Analyze the full list of products from the previous task. For each
    product, conduct keyword research for '{product_type}' targeting '{target_audience}'.
    Then, write a new, compelling, and SEO-optimized title (max 70 chars) and 
    description (max 160 chars) that reflects our '{brand_voice}'.
    
    You MUST use the 'Update Product SEO' tool for EACH product one-by-one
    to apply your new title and description.
  expected_output: >
    A confirmation log stating that each product's SEO has been updated. 
    For example: "Successfully updated SEO for product ID 12345. Successfully 
    updated SEO for product ID 12346." for all products.

marketing_campaign_task:
  description: >
    Using the full list of newly-optimized products and their SEO descriptions, 
    develop a single, creative marketing campaign idea to promote the 
    entire product line. The campaign should be tailored to our '{target_audience}' 
    and reflect our '{brand_voice}'.
  expected_output: >
    A single JSON object with a 'title' for the campaign and a 'body' 
    for the main ad copy, as defined in the 'Copy' Pydantic model.